### ISSUE TITLE
pas de release - pas de zip à telecharger

### ISSUE THREAD

**Issue by efhache** [lesscouts/template-unite#1]
Pas réellement un bug lié au code, mais actuellement le lien vers le fichier zip ne fonctionne pas car vous n'avez publié aucune release... 
pourriez-vous procéder à la publication ?  je souhaiterais vérifier dans quelle mesure il est possible d'utiliser ce template pour le renouvellement du site de l'unité où je suis parent aidant.

**Comment by ChMat** [comment]
Voilà qui est fait, cette première version est un premier ballon d’essai. N’hésite pas à nous remonter tes remarques !

https://github.com/lesscouts/template-unite/releases/tag/v1.0-beta.1

**Comment by efhache** [comment]
Merci beaucoup, entre temps je suis parti sur un autre template pour répondre au besoin de l'unité.  Mais je prends l'exercice courant décembre.
Je vous tiens informé.
