### ISSUE TITLE
modification de l'html inscription

### ISSUE THREAD

**Issue by emilien-Michel** [lesscouts/template-unite#4]
je recopie l'html de l'index dans la page inscription pour avoir la même en tête mais ne change. comment puis je faire pour avoir la même en tête sur toute les pages et comment les relier entre elles ?

**Comment by ChMat** [comment]
Bonjour,

Les exemples sont juste des pages statiques. Si tu veux réutiliser les mêmes morceaux de contenu (ici l’en-tête), tu as plusieurs solutions : 

- faire du copier-coller
- utiliser un éditeur de site web sur ton ordinateur (par exemple, [Silex](https://www.silex.me/))
- passer à un site généré par un CMS ([Wordpress](https://wordpress.org/) est le plus connu)

Un autre utilisateur a proposé un thème pour Wordpress dans le pull request #3 qui utilise ce template. Nous ne l’avons pas encore testé, mais tu peux tenter l’expérience.
